name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  install-dependencies: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code ğŸ‰
        uses: actions/checkout@v3
      - name: Run installation of dependencies ğŸš€
        run: npm install
      
  unit-testing:
    needs: install-dependencies 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code ğŸ‰
        uses: actions/checkout@v3
      - name: Run installation of dependencies ğŸš€
        run: npm install
      - name: Perform unit testing ğŸ
        run: npm test

    
  job-3: 
    runs-on: ubuntu-latest
    env: 
        secret: ${{ secrets.MY_SECRET}}
    steps:
    - name: Name reveal
      run: echo "ğŸ”ğŸ”ğŸ” This is top secret ${secret} " | sed 's/./& /g'